#!/usr/bin/env python3
"""
covers.py — deterministic cover/remix detection data + helpers.

This is intentionally *data-first* so it is easy to extend: add a word to a list
and the S5 signal picks it up. `detect_cover_signals()` scans normalized text
(filename + folder) and returns the concrete hits, so the review UI can show the
human *exactly which words* triggered the COVER verdict.
"""

import re

# --- Cover / arrangement / derivative-version indicators -----------------------
# Matched as whole tokens or substrings against NFKC-normalized, lowercased text.
COVER_KEYWORDS = [
    # English
    "cover", "covered by", "covered", "remix", "remixed", "bootleg",
    "nightcore", "slowed", "reverb", "sped up", "speed up", "spedup",
    "arrange", "arrangement", "rearrange", "flip", "mashup", "mash up",
    "piano ver", "piano version", "acoustic", "instrumental", "off vocal",
    "karaoke", "8bit", "8-bit", "chiptune", "orchestral", "metal ver",
    "lofi", "lo-fi", "male ver", "female ver", "english ver", "eng ver",
    # Japanese
    "歌ってみた",   # "tried to sing" — utaite cover
    "歌わせて",     # "let me sing"
    "アレンジ",     # arrange
    "カバー",       # cover
    "リミックス",   # remix
    "弾いてみた",   # "tried to play"
    "演奏してみた",
    "耳コピ",       # ear-copy transcription
]

# Free-standing version markers (word-boundary matched to avoid false hits inside words).
# NOTE: "feat." is deliberately NOT here. It's a collaboration credit that appears in
# countless official titles ("Might+U [feat. Jonatan King]"), and treating it as a
# cover signal blanked the album on catalog-confirmed official releases.
VERSION_MARKERS = [
    r"\bcv\.?\b",        # character-voice credit → almost always a cover/derivative
    r"\bver\.?\b",       # "ver." / "ver"
]

# --- Vocaloid / UTAU / synth-voice voicebank names -----------------------------
# A track "sung" by one of these is a synth cover, not the original artist.
# Keep extending this list — it is the whole point of having covers.py be data.
VOICEBANK_NAMES = [
    # Crypton / major Vocaloid
    "hatsune miku", "miku", "初音ミク", "ミク",
    "kagamine rin", "kagamine len", "rin", "len", "鏡音",
    "megurine luka", "luka", "巡音ルカ",
    "meiko", "kaito", "gumi", "megpoid",
    "kaai yuki", "kasane teto", "teto", "重音テト",
    "flower", "v flower", "gackpoid", "gakupo",
    "ia", "una", "otomachi una", "sekka yufu",
    # UTAU / CeVIO / Synth V common
    "defoko", "namine ritsu", "sukone tei",
    "kafu", "kotonoha", "akane", "aoi", "sasara",
    "adachi rei", "chis-a", "solaria", "eleanor forte",
]

# --- Topic channels: YouTube Music auto-generated official artist channels ------
# "Artist - Topic" channels are generated by YouTube from official label metadata,
# so the channel name (minus "- Topic") is a RELIABLE artist identity — never a
# cover. This is a positive MATCH signal, handled by the Topic fast-pass in
# verify.py (not a neutral channel). See is_topic_channel / topic_channel_artist.
TOPIC_SUFFIX_RE = re.compile(r"\s*-\s*topic\s*$", re.IGNORECASE)

# --- Neutral channels: auto-generated / label / aggregator uploaders -----------
# When the folder is one of these, it says nothing about MATCH vs COVER (S6 neutral).
# NOTE: "- Topic" is deliberately NOT here — it's a trust signal, not neutral.
NEUTRAL_CHANNEL_PATTERNS = [
    r"\bvevo\b",
    r"\bofficial\b",
    r"\brecords\b",
    r"\bentertainment\b",
    r"\bmusic\b$",
    r"\b1thek\b",
    r"\bsmtown\b",
    r"\bhybe\b",
    r"\bstone music\b",
    r"\bkakao\b",
    r"\bavex\b",
    r"\bsony music\b",
    r"\buniversal\b",
    r"\bcolou?r coded\b",
    r"\blyrics?\b",
]

_VERSION_RE = [re.compile(p, re.IGNORECASE) for p in VERSION_MARKERS]
_NEUTRAL_RE = [re.compile(p, re.IGNORECASE) for p in NEUTRAL_CHANNEL_PATTERNS]


def detect_cover_signals(text):
    """
    Scan text (already NFKC-normalized recommended) for cover indicators.

    Returns a list of dicts: [{'term': 'nightcore', 'kind': 'keyword'}, ...]
    Empty list == no cover indicators found.
    """
    if not text:
        return []
    low = text.lower()
    hits = []
    seen = set()

    for kw in COVER_KEYWORDS:
        if kw in seen:
            continue
        kwl = kw.lower()
        # ASCII keywords must match on word boundaries so "cover" doesn't fire on
        # "Groove Coverage" / "discover" / "recovery". CJK keywords have no word
        # boundaries, so substring matching is correct for 歌ってみた / カバー etc.
        if kw.isascii():
            matched = re.search(rf"\b{re.escape(kwl)}\b", low) is not None
        else:
            matched = kwl in low
        if matched:
            hits.append({"term": kw, "kind": "keyword"})
            seen.add(kw)

    for rx in _VERSION_RE:
        m = rx.search(text)
        if m and m.group(0) not in seen:
            hits.append({"term": m.group(0), "kind": "version"})
            seen.add(m.group(0))

    for vb in VOICEBANK_NAMES:
        # Require a word-ish boundary for short romaji names to avoid "luka" in "flukas".
        if len(vb) <= 4:
            if re.search(rf"\b{re.escape(vb)}\b", low) and vb not in seen:
                hits.append({"term": vb, "kind": "voicebank"})
                seen.add(vb)
        elif vb.lower() in low and vb not in seen:
            hits.append({"term": vb, "kind": "voicebank"})
            seen.add(vb)

    return hits


def is_neutral_channel(folder_name):
    """True if the folder is a label / aggregator / auto-generated channel (S6 neutral)."""
    if not folder_name:
        return False
    return any(rx.search(folder_name) for rx in _NEUTRAL_RE)


def is_topic_channel(folder_name):
    """
    True if the folder is a YouTube Music "Artist - Topic" auto channel. These are
    generated from official label metadata, so the channel artist is a reliable
    identity (never a cover) — a positive trust signal, not a neutral one.
    """
    if not folder_name:
        return False
    return TOPIC_SUFFIX_RE.search(folder_name) is not None


def topic_channel_artist(folder_name):
    """
    The artist identity from an "Artist - Topic" channel (the "- Topic" suffix
    stripped), or None if this isn't a Topic channel.
    """
    if not is_topic_channel(folder_name):
        return None
    artist = TOPIC_SUFFIX_RE.sub("", folder_name).strip()
    return artist or None
